### ISSUE TITLE
laravel 7.0 support not available

### ISSUE THREAD

**Issue by mrzainulabideen** [jarektkaczyk/eloquence-base#24]
Please add support for laravel 7.0 and above

**Comment by ahmad-saad** [comment]
I create a temp package in

https://packagist.org/packages/enbit/eloquence

it use the namespace as the orignal package.

I didn't change anything I just accept the version 7 as I said in the last comment.

you can use it until the owner make his changes.

Regard's

**Comment by jarektkaczyk** [comment]
tagged bump to L7
